
eureka:
  instance:
    prefer-ip-address: true
    appname: customerCenter
  client:
    enabled: true
    healthcheck:
      enabled: false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka


server:
  port: 8003

liquibase:
  enabled: true

spring:
  application:
    name: customerCenter

      #  profiles:
      #    active: dev
      #    include:
      #      - swagger
      # Uncomment to activate TLS for the dev profile
    #- tls

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.99.204.53:3306/customer_center?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false
    username: root
    password: 12301
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: MYSQL
#    show-sql: false
#    properties:
#      hibernate.id.new_generator_mappings: true
#      hibernate.connection.provider_disables_autocommit: true
#      hibernate.cache.use_second_level_cache: false
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false

      hibernate.multiTenancy: DATABASE
      hibernate.tenant_identifier_resolver: com.shicc.customercenter.tenant.MultiTenantIdentifierResolver
      hibernate.multi_tenant_connection_provider: com.shicc.customercenter.tenant.MultiTenantConnectionProviderImpl

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: saas-tenant
      auto-commit-interval: 100
      auto-offset-reset: latest
      # true offset交给kafka来管理，offset进行默认的提交模式
      # false offset交给Spring手工提交
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      tenant-data-source-info: ${application.kafka-topics.tenant-data-source-info}

    bootstrap-servers: localhost:9092


application:
  kafka-topics:
    tenant-data-source-info: tq-uaa-tenant-data-source-info-topic



